### ISSUE TITLE
［标签tab页切换组件］中的Tab.Item的Title是否可以固定？

### ISSUE THREAD

**Issue by wflashy** [saltjs/salt-ui#10]
［标签tab页切换组件］中的Tab.Item的Title是否可以固定？
  当Item的内容过多时，Title也会随着屏幕滚动而滚动，是否把Title可以设置成固定在顶端？像TabBar固定在底部一样！

**Comment by gbk** [comment]
试一下 `fixedTop` 属性吧

```
<Tab fixedTop>
  <Tab.Item>
  </Tab.Item>
</Tab>
```

**Comment by wflashy** [comment]
fixedTop 属性 不能解决该问题。

不过我通过修改 styl 的方式 可以解决该问题,实现固定。
.t-tab-head
    position:fixed
    z-index:99999
.t-tab-body
   padding: 50px 0 0 0
