### ISSUE TITLE
 t.context.router.push(route);

### ISSUE THREAD

**Issue by wflashy** [saltjs/salt-ui#11]
demo中的t.context.router.push(route) 可以传参数吗？
比如像这样的：
salt.router.push({
        id:'xxx', // frame id 
        url:'xxx', // 跳转的frame 所需要加载的url
        anim:1, // 转场动画,1:从左到右,2:bottom 从下往上;默认1;
        needPost:true // 是否需要发送数据到加载的frame; 
        param:'xxx' // 当needPost 是true的时候发送的数据
}).then(()=>{}).catch((e)=>{
})

**Comment by dongruiyang** [comment]
可以~参数对象都可以放在param 上~

**Comment by 2999** [comment]
请查看[react-router](https://github.com/ReactTraining/react-router)相关版本的api
