### ISSUE TITLE
Tab组件使用疑问！

### ISSUE THREAD

**Issue by chitu90** [saltjs/salt-ui#14]
请问Tab和TabBar能同时使用吗，使用中发现在页面内容使用Tab，底部使用TabBar的事件会失效，点击不了，另外Tab能和redux配合使用吗？在使用过程中发现，当redux状态树与使用Tab页面的组件进行绑定后，即使状态数据发生改变，页面也不会执行render方法，求解！

**Comment by chitu90** [comment]
使用了Tab组件之后控制台会报以下错误，不知道何原因

reactProdInvariant.js:32Uncaught Invariant Violation: Minified React error #119; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=119 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by gbk** [comment]
把你的代码贴一下？
估计是 Tab.Item 写成了 Tab.item

**Comment by chitu90** [comment]
![image](https://cloud.githubusercontent.com/assets/16437001/18939382/7b1f448a-8632-11e6-828e-6de2c5876e64.png)

页面可以正常显示，只是控制台会报错，跟Tab.Item没关系，我只要在页面引用了Tab组件里面不写其他东西控制台都会报错，另外我所搭的环境并不是官网上所推荐的nowa环境，我就在node环境下开发同样用的是webpack做编译部署，不知是否有关系，上面提到的“请问Tab和TabBar能同时使用吗，使用中发现在页面内容使用Tab，底部使用TabBar的事件会失效”，也请您帮忙回答一下
![image](https://cloud.githubusercontent.com/assets/16437001/18939318/004cd394-8632-11e6-9aee-f89a5673cdad.png)

**Comment by chitu90** [comment]
let { Group, Tab, List, Avatar, Button, Boxs, Icon} = SaltUI;
let HBox = Boxs.HBox;
let Box = Boxs.Box;

class WorkBench extends React.Component {
    constructor(props) {
        super(props);
    }
    handleChange() {
        console.log('change................');
    }
    render() {
        let t = this;
        return (
            <Tab active={0} className="page-list" onChange={this.handleChange}>
                <Tab.Item title="业绩展示">
                    <Tab type={'brick'} active={0}>
                        <Tab.Item title="上月" >
                            
                            
                        </Tab.Item>
                        <Tab.Item title="本月" >
                            
                            
                        </Tab.Item>
                    </Tab>
                </Tab.Item>
                <Tab.Item title="待办提醒"></Tab.Item>
            </Tab>
        )
    }
}

module.exports = WorkBench;

**Comment by gbk** [comment]
Tab 和 TabBar 可以同时使用的，估计是有报错。

你给出的代码 render 里是空的？

你把页面中引用的 react 换成没有 minify 的版本吧，看一下具体是什么异常

**Comment by chitu90** [comment]
![image](https://cloud.githubusercontent.com/assets/16437001/18939635/2647ca2a-8634-11e6-80bd-235e40ac5fe0.png)
代码如图所示
![image](https://cloud.githubusercontent.com/assets/16437001/18939644/41530974-8634-11e6-88cd-346f303eb186.png)

效果如图所示，页面底部的TabBar点击是无效的，冒昧的问下，如何将react中的版本换成minify版？

**Comment by gbk** [comment]
你找到页面中引入 react 的地方，截图发我

**Comment by chitu90** [comment]
![image](https://cloud.githubusercontent.com/assets/16437001/18939709/ce592614-8634-11e6-9d14-cf65cde376a7.png)
这是页面入口所引入的一些库

**Comment by gbk** [comment]
html 中 引入 script 的地方

**Comment by chitu90** [comment]
![image](https://cloud.githubusercontent.com/assets/16437001/18939775/5669aace-8635-11e6-935d-080e22bb345b.png)

**Comment by gbk** [comment]
react-dom.min 换成 react-dom 吧

**Comment by kangning1206** [comment]
使用钉钉联系下: 张顺

**Comment by kangning1206** [comment]
我贴下我试验的结果：

## html 资源和版本

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>test_tab</title>
<meta name="HandheldFriendly" content="True">
<meta name="MobileOptimized" content="320">
<meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
<meta http-equiv="cleartype" content="on">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="apple-mobile-web-app-title" content="">
<meta name="format-detection" content="telephone=no">
<meta name="format-detection" content="email=no">

<!-- 外部样式资源加载 -->
<link rel="stylesheet" href="//g.alicdn.com/platform/tingle-ui/1.0.27/salt-ui.min.css">

<!-- 项目样式资源加载 -->
<link rel="stylesheet" href="/app.css">

<!-- 外部脚本资源加载 -->
<script src="//g.alicdn.com/platform/c/??zepto/1.1.6/zepto.min.js,react/0.14.3/react-with-addons.min.js,react/0.14.3/react-dom.min.js,react-router/2.0.0/umd/ReactRouter.min.js,fastclick/1.0.6/lib/fastclick.min.js,reflux/0.3.0/dist/reflux.min.js,lie/3.0.2/dist/lie.polyfill.min.js,salt-fetch/2.0.3/dist/salt-fetch.min.js,salt-router/0.0.2/salt-router.min.js"></script>
<script src="//g.alicdn.com/dingding/open-develop/0.6.4/dingtalk-ali.js"></script>
</head>
<body>

<div id="App"></div>
<script src="//g.alicdn.com/platform/tingle-ui/1.0.13/salt-ui.min.js"></script>

<!-- 项目脚本资源加载 -->
<script src="/app.js"></script>
</body>
</html>

```

## jsx 文件

```

const reactMixin = require('react-mixin');
const Actions = require('./actions');
const Store = require('./store');

const { Tab,TabBar } = SaltUI;

class Demotab extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            tabActiveIndex: 0,
            barActiveIndex:0
        };
    }

    render() {
        let t = this;
        return (
            <div className="demotab">
                {
                    t._renderTab()
                }
                {
                    t._renderBar()
                }
            </div>
        );
    }
    handleTabChange(tab) {
        console.log(tab.active);
    }

    handleBarChange(activeIndex){
        this.setState({
            barActiveIndex: activeIndex
        });
    }

    _renderBar(){
        let t = this;
        return (<TabBar activeIndex={this.state.barActiveIndex} onChange={t.handleBarChange.bind(t)}>
                <TabBar.Item title="工作台"></TabBar.Item>
                <TabBar.Item title="CRM"></TabBar.Item>
                <TabBar.Item title="资讯"></TabBar.Item>
                <TabBar.Item title="我的"></TabBar.Item>
            </TabBar>);
    }

    _renderTab(){
        let t = this;
        return (<Tab active={t.state.tabActiveIndex} onChange={t.handleTabChange.bind(t)}>
                    <Tab.Item title="业绩展示">
                         <Tab active={0} type='brick'>
                            <Tab.Item title="上月">
                                <div className="t-LH1_5 t-P10">
                                    这里是上月 单据信息
                                </div>
                            </Tab.Item>
                            <Tab.Item title="本月">
                                <div className="t-LH1_5 t-P10">
                                    这里是本月 单据信息...
                                </div>
                            </Tab.Item>
                        </Tab>
                    </Tab.Item>
                    <Tab.Item title="待办提醒">
                        <div className="t-LH1_5 t-P10">
                            待办提醒...
                        </div>
                    </Tab.Item>
                </Tab>);
    }
}

reactMixin.onClass(Demotab, Reflux.connect(Store, 'Demotab'));

module.exports = Demotab;




```

## 效果和控制台

![image](http://git.cn-hangzhou.oss.aliyun-inc.com/uploads/tingle-ui/tingle-tab-bar/4b1df71224d1c8c9f4d2787af0c2d8ba/image.png)

**Comment by kangning1206** [comment]
为了错误信息显示的更清晰，建议将html文件中资源文件中min文件更改掉，

更改前

```
react/0.14.3/react-with-addons.min.js,react/0.14.3/react-dom.min.js,
```

更改后

```
react/0.14.3/react-with-addons.js,react/0.14.3/react-dom.js,
```

**Comment by kangning1206** [comment]
我的例子代码在：https://github.com/kangning1206/test_tab
底部bar事件可以点击

**Comment by chitu90** [comment]
我的，我先测试一下

**Comment by chitu90** [comment]
我去掉min之后所报的错误也都是一样的，下面是我的测试工程

我测了一下你上面的例子可以用，不过我们公司这边的环境跟你们那边的环境不一样，我们没有使用nowa，以及我们使用的是redux，不是ReFlux，我们这套环境在PC端也使用，我们是希望统一PC端及移动端的开发环境，现在是在集成SaltUI时发现Tab组件才会有问题，其他组件暂时未发现问题，因为还不能定位问题的原因，我们不想因此改变使用的Redux框架，希望RT可以帮忙支持一下，如果确认SaltUI对环境或者ReFlux有依赖，我们这边再考虑改，谢谢

**Comment by kangning1206** [comment]
SaltUI是UI层的，state管理relfux和redux是不冲突的，你的代码我下载下来尝试运行。

**Comment by kangning1206** [comment]
大概原因是react版本冲突了；

## html页面

在index.html文件中，使用

```
<script src="//g.alicdn.com/platform/c/??zepto/1.1.6/zepto.min.js,react/0.14.3/react-with-addons.js,react/0.14.3/react-dom.min.js,react-router/2.0.0/umd/ReactRouter.min.js,fastclick/1.0.6/lib/fastclick.min.js,lie/3.0.2/dist/lie.polyfill.min.js,natty-db/1.0.2/dist/natty-db.min.js,reflux/0.3.0/dist/reflux.min.js"></script>
```

已经引入了react资源，且版本是0.14.3版本，会在window下暴漏出全局React,ReactDOM两个变量；

紧接着
引入了salt-ui了，其中salt-ui使用前，必须存在react,react-dom，也就是说salt-ui是用来与他们两个的，顺序不能乱；

```
<script src="//g.alicdn.com/platform/tingle-ui/1.0.13/salt-ui.min.js"></script>
```

## jsx文件

> 这里是重点

比如 WorkBench.jsx 文件源码

```
import React, { Component, PropTypes } from 'react';

```

需要更改为

```
let { Component, PropTypes } = React;

```

WorkBench.jsx 文件中的 from 'react' 版本是package.json中描述的 "react": "^15.1.0",    "react-dom": "^15.0.1", 是否必须版本相同，我没有测试，至少这里有重复引入；

另外一个重点是 salt-ui 组件是0.14.*版本的；

## 结论

我建议使用html中引入的全局react资源，jsx不要在require react，尤其是react-dom更容易出问题，直接使用，避免重复和冲突；同时者也是唯一的方式，必须在html页面映入react相关资源，因为salt-ui.min.js是依赖它们的；
另一个考虑的问题，react和react-dom是资源文件，也没必要打包到bundle文件中，增加体积和不稳定性；

如果你们项目使用了15.1.0版本的react，我尝试更改版本后，与salt-ui是兼容的，控制台没错误；

总之，一句话`注意react相关文件的重复，在jsx文件不要再 require('react'),require('react-dom') 资源了，就使用html中引入的`

```
<script src="//g.alicdn.com/platform/c/??zepto/1.1.6/zepto.min.js,react/15.1.0/react-with-addons.js,react/15.1.0/react-dom.min.js,react-router/2.0.0/umd/ReactRouter.min.js,fastclick/1.0.6/lib/fastclick.min.js,lie/3.0.2/dist/lie.polyfill.min.js,natty-db/1.0.2/dist/natty-db.min.js,reflux/0.3.0/dist/reflux.min.js"></script>
```

**Comment by chitu90** [comment]
非常感谢！！
