### ISSUE TITLE
ScrollList  这个怎么使用，文档能出个吗？

### ISSUE THREAD

**Issue by shenggen1987** [saltjs/salt-ui#15]

**Comment by gbk** [comment]
http://alinw.alicdn.com/platform/tingle-ui/1.1.9/docs/docs.html#tingle-scroll-list

**Comment by shenggen1987** [comment]
谢谢，&lt;ItemOne/&gt;
         &lt;ItemTwo/&gt;
         &lt;RepeatItem/&gt;  这三个组件是怎么写的？求解

**Comment by gbk** [comment]
ItemOne、ItemTwo 这些只是示例，你可以换成 div

**Comment by 2999** [comment]
ItemOne、ItemTwo 、RepeatItem只是示例。
只有放在ScrollList中的最后一个元素（比如上面说的RepeatItem）才会被render成list。
因为在某些场景下可能会在列表上方放置一些其它元素，比如搜索框等。

**Comment by 373706818** [comment]
你写个例子,比什么都强!
我转了一下午了,没弄明白,怎么用.

东西是你做的,你肯定觉得使用 很简单.
你写个简单能真正跑起来的例子,对其他不熟悉的使用者来说,方便多了.

最后,希望能写个例子.
