### ISSUE TITLE
salt的需求和建议

### ISSUE THREAD

**Issue by ghost** [saltjs/salt-ui#17]
1. badge
   可以独立使用的小徽章,也可以附加到list,tabbar等上.用作数目或者标签提示. 

2. style
   这个的适用范围是? 有些组件怎么设置了,没有作用?

3. 九宫格, 内置的子项图片太小了,就不居中了.

**Comment by ghost** [comment]
??

**Comment by 2999** [comment]
@xttianma ：
1、badge会支持，已排入计划；
2、没明白你的意思；
3、请使用salt-ui最新版本的js和css：http://g.alicdn.com/platform/tingle-ui/1.1.12/salt-ui.min.js、http://g.alicdn.com/platform/tingle-ui/1.1.12/salt-ui.min.css

**Comment by 2999** [comment]
salt-ui V3灰度中，即将发布
