### ISSUE TITLE
请教源代码和npm版本预计何时会发布

### ISSUE THREAD

**Issue by tonylinyy** [saltjs/salt-ui#2]
如题,
公司在钉钉项目中在评估采用哪个组件库比较合适,当然首选是salt-ui,因为我们的前端小伙伴也是用的react
只是团队想了解下salt-ui发布的大致时间,好心里有数,谢谢

**Comment by alex-mm** [comment]
您好
    目前团队内正在对 salt-ui 进行完善，包括组件增强、增加单元测试覆盖率等，完成后我们会找合适的时间开源，到时一定第一时间通知您，感谢您的支持。
