### ISSUE TITLE
setTitle方法在安卓导航里只闪现，又回到最初的导航栏名字了

### ISSUE THREAD

**Issue by qhj1990** [saltjs/salt-ui#20]
setTitle方法在安卓导航里只闪现，又回到最初的导航栏名字了。在ios里settitle方法，导航栏的title会成功变化

**Comment by gbk** [comment]
dd.ready 之后再执行 settitle 试试看呢

**Comment by qhj1990** [comment]
dd.ready之后执行， 安卓版会中间显示网页的<title></title>里的值，最后变成settitle设置的title。官方demo在安卓版里也有这个问题。建议官方demo里也加dd.ready

**Comment by gbk** [comment]
已更新
