### ISSUE TITLE
总结一下salt还需要的组件

### ISSUE THREAD

**Issue by ghost** [saltjs/salt-ui#21]
-------------与amaze相比---------------------: 
# 1. Badge 组件(数字红点):
> 据了解，tabBar已经在排期了.
> list的红点用group.list传入jsx实现,怎么实现呢?本人还不会,期望一个demo.

# 2. Breadcrumb(面包屑)
> 用在组织架构的层级和省地市的节点告知. 什么时候可有呢?

# 3. slide (幻灯片)
> 为啥style={{backgroundImage: "http://xxx.jpg"}} 设置的图片不显示呢?应该怎么用呢?

# 4. style (底层样式)
>能否按钉钉的规范，做一个style包，对当前的style重新组合一下, 适配不同的产品？一大堆的t-FAL．．．．链接起来，阅读理解和使用上比较困难. 

# 5. Typography(排版)
> 学习一下amaze, 对文字排版做一个规范使用, 方便统一文字大小,开发快捷. 
补充:　http://g.alicdn.com/platform/tingle-ui/1.1.0/docs/docs.html#tingle-style
在这里，文字和　底层样式的定义．．．．（不习惯的时候，还是好难理解呀）

# 6 . Notification(通知)
> 弹出的这个很使用呀. 

# 7. 固定元素
      底部浮动或者顶部浮动.....

-----对比ant的移动端组件-----------
# 1. Accordion(手风琴)
> 实现下花菜单或手风琴效果, 

# 2. ActionSheet 动作面板

# 3 .....   Ant UI的好丰富呀没有办法一一说了. 

--------------------------------------------------------

**Comment by 2999** [comment]
@xttianma 收到，非常谢谢

**Comment by 2999** [comment]
salt-ui V3灰度中，即将发布
