### ISSUE TITLE
关于className="t-FS20 t-PL6"的文字字号调整无效的问题?

### ISSUE THREAD

**Issue by ghost** [saltjs/salt-ui#22]
请看这两张图红圈的文字size. 
className="t-FS20 t-PL6"

t-PL6 调整有效果,  t-FS20 这个修改字号,有反应(闪现模糊一下),但是字号始终不增大.

![image](https://cloud.githubusercontent.com/assets/22427990/20667659/58a21d5e-b5a5-11e6-88c6-cc5ea686a5dd.png)

![image](https://cloud.githubusercontent.com/assets/22427990/20667668/5e1fb62e-b5a5-11e6-96f4-5bb7eea187a2.png)

`         <Group >
                <Group.List className="t-FS20 t-PL6" borderTopNone >
                    <List 
                        onClick={this.handleClick.bind(this)}
                        data={[{
                            title : this.props.label,
                            value : 'sdfafd'
                        }]}
                    /> 
                </Group.List>
            </Group>`

**Comment by 2999** [comment]
List组件在内部对title指定了字号和行高，这是为了保证list-item不会因为外部继承过来的字号和行高导致错乱。
解决你的问题的方法有两种：
1、使用List组件，并自定义样式来覆盖List的相关样式；
or
2、不使用List组件，Group.List中的内容由你自定义。
