### ISSUE TITLE
地址栏变动了三次，如何减少

### ISSUE THREAD

**Issue by qhj1990** [saltjs/salt-ui#25]
使用salt-ui后，阿里h5测试工具显示  首页会重定向两次，
一次是加了        url#/  
另一次 是变成   url#/?_k=bfdr6n
如何减少重定向

**Comment by gbk** [comment]
hash 变更不会触发重新渲染，这块是 react-router 的默认行为。
为什么要减少重定向呢？是遇到什么问题了吗？
