### ISSUE TITLE
SearchBar组件的页面使用Scroller组件后,无法正常弹出搜索画面.

### ISSUE THREAD

**Issue by ghost** [saltjs/salt-ui#28]
结构如下. 

> <div>

                <div > 
                    <SearchBar 
                        placeholder='搜索人员' 
                        hasHistory={true} 
                        historyName='USER_LIST_SEARCH_HISTORY'
                        onSearch={t.handleOnSearch.bind(value)}                    
                        />
                </div>
                <Scroller>
                    <Group  >
                           ......
                    </Group>
                </Scroller>
            </div>`

**Comment by gbk** [comment]
栗子奉上 :smiley: 

PageDemo.js
```jsx
const { Component } = React;
const { SearchBar, Scroller, Group } = SaltUI;

require('./PageDemo.styl');

class Page extends Component {

    constructor(props) {
        super(props);
        this.state = {};
    }

    handleSearch(key) {
        console.log(`Searching with ${key}...`);
        // TODO do somthing with key, and set the search result.
        const result = new Array(10);
        result.fill(`Search result with '${key}'`);
        this.setState({
            result,
        });
    }

    render() {
        let t = this;
        return (
            <SearchBar onSearch={t.handleSearch.bind(t)}>
                <Scroller>
                    <Group>
                        <Group.List>
                            {
                                t.state.result && t.state.result.length ?
                                    t.state.result.map((n) => <div className="t-LH44">{n}</div>)
                                    : ''
                            }
                        </Group.List>
                    </Group>
                </Scroller>
            </SearchBar>
        );
    }
}

module.exports = Page;
```

PageDemo.styl
```styl
.t-scroller
    position fixed
    top 46px
    right 0
    bottom 0
    left 0
```

**Comment by ghost** [comment]
出现的问题: 
当SearchBar 下面有Tabbar组件的时候, 点击"搜索",在弹出的输入页面,""取消""按钮失效(不返回之前页面)

>  <div className="page-home">
                <SearchBar onSearch={t.handleSearch.bind(t)}>
                    <Scroller>
                        <Group>
                            <Group.List>
                                {
                                    t.state.result && t.state.result.length ?
                                        t.state.result.map((n) => <div className="t-LH44">{n}</div>)
                                        : ''
                                }
                            </Group.List>
                        </Group>
                    </Scroller>
                </SearchBar>

                <Scroller>
                    <CurrentPage />                        
                </Scroller>
            
                <TabBar activeIndex={t.state.activeIndex} onChange={t.onChange.bind(t)}>
                    <TabBar.Item title="XX1" icon="user" />                    
                    <TabBar.Item title="XX2" icon="star" />
                    <TabBar.Item title="XX3" icon="map" />
                    <TabBar.Item title="XX4" icon="search" />
                    <TabBar.Item title="XX5" icon="user" />
                </TabBar>
                
            </div>

**Comment by gbk** [comment]
我没能重现呢。。可能跟你其他地方的逻辑有关。
```jsx
const { Component } = React;
const { SearchBar, Scroller, Group, TabBar } = SaltUI;

require('./PageDemo.styl');

class Page extends Component {

    constructor(props) {
        super(props);
        this.state = {};
    }

    handleSearch(key) {
        console.log(`Searching with ${key}...`);
        // TODO do somthing with key, and set the search result.
        const result = new Array(10);
        result.fill(`Search result with '${key}'`);
        this.setState({
            result,
        });
    }

    handleTabClick() {
    }

    render() {
        let t = this;
        return (
            <div>
                <SearchBar onSearch={t.handleSearch.bind(t)}>
                    <Scroller className="search-content">
                        <Group>
                            <Group.List>
                                {
                                    t.state.result && t.state.result.length ?
                                        t.state.result.map((n) => <div className="t-LH44">{n}</div>)
                                        : ''
                                }
                            </Group.List>
                        </Group>
                    </Scroller>
                </SearchBar>
                <Scroller className="page-content">
                    page content
                </Scroller>
                <TabBar activeIndex={t.state.activeIndex} onChange={t.handleTabClick.bind(t)}>
                    <TabBar.Item title="XX1" icon="user" />
                    <TabBar.Item title="XX2" icon="star" />
                    <TabBar.Item title="XX3" icon="map" />
                    <TabBar.Item title="XX4" icon="search" />
                    <TabBar.Item title="XX5" icon="user" />
                </TabBar>
            </div>
        );
    }
}

module.exports = Page;
```

**Comment by LiangZugeng** [comment]
借宝地问一下相关问题。

我想实现的功能是进入页面先加载并显示全部列表，最上面是SearchBar，然后点击SearchBar的搜索框，输入关键字，下面的列表刷新为搜索后的新数据。

按照@gbk的示例，列表是SearchBar的子元素，我测试后发现只有当SearchBar搜索后子元素才显示出来，刚进入的时候即使加载了数据也不会把列表渲染出来。

我尝试把列表移到SearchBar的外面（而并不是作为子元素），进入页面时可以正常显示列表，但是搜索的时候SearchBar又不会自动隐藏，只能每次搜索完毕都点击“取消”按钮返回上一个页面，这样列表才能显示出来。

麻烦帮忙看看如何能更好地完成我的目的。谢谢。

Sample Code Repo: https://github.com/LiangZugeng/searchBarQuestion.git/

0. Make sure nowa has been installed.
1. Git clone https://github.com/LiangZugeng/searchBarQuestion.git/
2. cd searchBarQuestion
3. npm run start
4. open browser and navigate to http://localhost:3000

**Comment by ghost** [comment]
@LiangZugeng 既然是搜索,列表肯定会很多, 为什么呢要加载显示全部列表? 这个体验有问题吧. 

可以参考的钉钉的搜索, 搜索框下面应该是常用关键字的小标签. 而不是你说的全部列表. 

你想实现的场景是否通讯录之类的? 可以滑动也可以查找?

**Comment by LiangZugeng** [comment]
谢谢建议。我们设计的这个页面有分页机制，第一次进入只加载一页内容，10条数据，不会太多，搜索框放在顶上是比较方便的做法。

根据控件的表现，我觉得SearchBar控件适合于这种场景：进入页面是列表，头上有个搜索图标，点击后进入新的搜索页面，然后进行搜索和返回。不知道理解对不对。

@gbk，也麻烦你给点建议，谢谢了。

**Comment by gbk** [comment]
> 进入页面是列表，头上有个搜索图标，点击后进入新的搜索页面，然后进行搜索和返回。

@LiangZugeng 我们现在的实现跟你的描述一致
@jzlingmo 看下能不能更好地满足 Liangzugeng 的需求

**Comment by jzlingmo** [comment]
@LiangZugeng 目前SearchBar的使用方式是将列表分成两个，一个是正常显示的列表（非<SearchBar />子元素），另一个是搜索结果列表（<SearchBar />子元素），两个列表不相互影响
```
onSearch(value){
  this.searchList.fetchData({
    keyword: value,
  });
}
...
<SearchBar onSearch={this.onSearch}>
  <List ref={(ref) => this.searchList = ref}/>
</SearchBar>
<List />
```

**Comment by LiangZugeng** [comment]
Issue closed, we will look to update the UI flow.
