### ISSUE TITLE
Tabbar与子组件div层级错乱造成被子组件遮盖的问题.

### ISSUE THREAD

**Issue by ghost** [saltjs/salt-ui#29]
tabbar成了子组件中Group内head和list的夹层. 不再是顶层组件了.如何解决?

**Comment by 2999** [comment]
<img src="https://cloud.githubusercontent.com/assets/1653891/20872380/ef6d79a8-bad8-11e6-8783-0c7c55500fa4.png" width="200" height="400" />

<img src="https://cloud.githubusercontent.com/assets/1653891/20872381/ef6ddaec-bad8-11e6-8be7-ac38d8652270.png" width="200" height="400" />

@xttianma 上面是你给的截图。

定位问题为tab-bar没有明确使用z-index。

![image](https://cloud.githubusercontent.com/assets/1653891/20872418/42ba417c-bad9-11e6-81ea-a0f7419c0629.png)

**Comment by 2999** [comment]
@gzlingmo

**Comment by 2999** [comment]
@jzlingmo

**Comment by ghost** [comment]
补充,@maqy , 使用补丁styl后, 还有一点小bug, 向上滑动最底部的一行,被tabbar所遮挡.

**Comment by 2999** [comment]
@xttianma 你@错了，那个人不是我。这个问题，截个图在这里哈

**Comment by jzlingmo** [comment]
@xttianma 由于只使用了tabTar的tab部分，没有使用tabContent，需要自己在body或者自己定义的content容器里面加上margin-bottom:50px或者padding-bottom:50px

**Comment by 2999** [comment]
已发布1.1.16，fixed
