### ISSUE TITLE
请教有没有可以用来上传图片的组件

### ISSUE THREAD

**Issue by huangda2100** [saltjs/salt-ui#38]

**Comment by gbk** [comment]
有

http://alinw.alicdn.com/platform/tingle-ui/1.2.0/docs/docs.html#tingle-photo-field

![image](https://cloud.githubusercontent.com/assets/865717/21968490/10e5bce0-dbd0-11e6-8077-c7abb236cb67.png)

**Comment by huangda2100** [comment]
十分感谢！ 但我遇到一个新问题：在钉钉中运行时，点击相机按钮，不会弹出相册或者牌照的选项，无法上传图片，如果知悉，请告知解决方法
