### ISSUE TITLE
请教PhotoField在钉钉手机客户端无法使用isDingDing undefined的问题

### ISSUE THREAD

**Issue by huangda2100** [saltjs/salt-ui#39]
使用photoField时，总是会报isDingDing没有定义，已经在钉钉客户端运行了，唯一的可能就是运行demo的域名不在钉钉白名单中，如果是白名单的问题，那白名单如何破？

**Comment by gbk** [comment]
![image](https://cloud.githubusercontent.com/assets/865717/22090923/181846fc-de2f-11e6-8adb-25cbd92eec08.png)
加一下钉钉群，可能你的配置有问题吧
