### ISSUE TITLE
@ali/tingle-icon-source 怎么安装

### ISSUE THREAD

**Issue by pkgplus** [saltjs/salt-ui#41]
http://g.alicdn.com/platform/tingle-ui/1.2.3/docs/docs.html#tingle-icon-source 里 @ali/tingle-icon-source怎样安装？

**Comment by gbk** [comment]
下载这份看看能不能跑起来
https://raw.githubusercontent.com/saltjs/salt-ui/master/demo/src/images/tingle-icon-symbols.svg

用法参考这里
https://github.com/saltjs/salt-ui/blob/master/demo/src/app/app.js#L4

**Comment by 2999** [comment]
时间太长，先关闭该issue。如果问题未解决，再打开
