### ISSUE TITLE
module device.network not found

### ISSUE THREAD

**Issue by huangda2100** [saltjs/salt-ui#44]
这个问题可有遇到过？ 如何解决？

**Comment by 2999** [comment]
@gbk 是否有遇到过？

**Comment by gbk** [comment]
https://open-doc.dingtalk.com/docs/doc.htm?spm=a219a.7629140.0.0.YQOlH6&treeId=171&articleId=104912&docType=1

我查了下文档，本来就没有 device.network 吧？
API 的问题在群里 at 李乔 吧
