### ISSUE TITLE
LIST 动态加载数据超过100条 手机上面就有点划不动了（卡顿）  

### ISSUE THREAD

**Issue by silentzone** [saltjs/salt-ui#45]
用grouplist 就不会有这个问题

**Comment by silentzone** [comment]
` <List   layout="left"
                                hasRightIcon={true}
                                isDelete={true}
                                onClick={t.itemClick.bind(t)}
                                data={ t.state.personList } />`

**Comment by gbk** [comment]
先用 grouplist 自己实现一下吧～list 我们后面安排优化。

**Comment by silentzone** [comment]
三克油 , 目前就这么做的辛苦了
