### ISSUE TITLE
如何引用salt-ui的最新版

### ISSUE THREAD

**Issue by LiangZugeng** [saltjs/salt-ui#47]
最近两天发现Salt-ui的参考文档更新了，统一到了https://salt-ui.github.io/components/tingle-button/。

我们不是阿里内部团队，不能安装使用tnpm，目前我们使用引用阿里CDN上的salt-ui.js的方式使用salt-ui，目前的问题是我们不知道最新版的Salt-ui版本是多少？应该使用哪个cdn url引用。

我们现在使用：
<link rel="stylesheet" href="//g.alicdn.com/platform/tingle-ui/1.2.0/salt-ui.min.css">
<script src="//g.alicdn.com/platform/tingle-ui/1.2.0/salt-ui.min.js"></script>

在这个Saltui版本中SelectField在Chrome 56.0.2924.87中有问题，选择框不能正常滚动，但我们发现在最新的salt-ui参考文档的SelectField示例中已经修复了此问题，所以想更新正在使用的salt-ui的版本。

请指导如何引用最新的salt-ui，如果能告知如何找到salt-ui的源代码就更好了。

注：尝试过了从CDN上使用1.2.6的salt-ui js文件，但提到的selectfield的bug还是存在。
<link rel="stylesheet" href="//g.alicdn.com/platform/tingle-ui/1.2.6/salt-ui.min.css">
<script src="//g.alicdn.com/platform/tingle-ui/1.2.6/salt-ui.min.js"></script>

**Comment by gbk** [comment]
`view-source:https://salt-ui.github.io/mobile/demos/tingle-button/basic`

这里可以看到...

你说的问题是不是这个？
https://github.com/LiangZugeng/scroller-bug-repro

这周我们把 scroller 更新掉，应该可以解决很多类似的问题。

**Comment by LiangZugeng** [comment]
@gbk ，谢谢您的回复。
https://github.com/LiangZugeng/scroller-bug-repro这个问题已经在您的指导下解决掉了，在使用Scroller控件的时候加上disablePointer就行了。

现在的问题不是这个，而是页面上SaltUI中的SelectField控件的问题，应该是老版本SelectField控件使用了iscroll但并没有加上disablePointer属性导致的，我认为只能使用你们的新的控件才能解决。

你们更新了scroller，那我怎么引用最新的版本呢？或者说我们怎么使用整个SaltUI的最新版本？刚才按照https://salt-ui.github.io/mobile/demos/tingle-button/basic源码中的引用把saltUI改为从下面地址引用：http://g.alicdn.com/platform/tingle-ui/1.2.10/salt-ui.min.js，1.2.10的salt-ui.min.js还是没能解决SelectField的滚动问题。请指教。

**Comment by gbk** [comment]
SelectField 也依赖 Scroller 的
@LiangZugeng 我的意思就是我们这周把 Scroller 默认加上那个参数，然后发个包 SelectField 之类依赖 Scroller 的组件也就都能用了

**Comment by LiangZugeng** [comment]
哦，明白了，也就是说你们还没有发布更新的包对吧？我以为https://salt-ui.github.io/mobile/demos/tingle-button/basic既然已经上线了，最新的版本我们外部用户就能马上使用了，其实是我想多了。:(

那就等着你们发布新的包吧，发布完成以后麻烦告知我通过何种方式可以使用最新的控件。谢谢。

**Comment by gbk** [comment]
@2999 发新包之后烦请在这里回复一下哦～

**Comment by 2999** [comment]
2017-3-16发布了1.2.11，之后就进入了2.x时代，具体变更请参考这里：https://salt-ui.github.io/components/tingle-ui
