### ISSUE TITLE
找个ScrollList的例子吧

### ISSUE THREAD

**Issue by 373706818** [saltjs/salt-ui#50]
你写个例子,比什么都强!
我转了一下午了,没弄明白,怎么用.

东西是你做的,你肯定觉得使用 很简单.
你写个简单能真正跑起来的例子,对其他不熟悉的使用者来说,方便多了.

最后,希望能写个例子.

**Comment by 2999** [comment]
https://salt-ui.github.io/components/tingle-scroll-list
