### ISSUE TITLE
关于引入images文件夹的图片资源

### ISSUE THREAD

**Issue by balddonkey** [saltjs/salt-ui#51]
使用相对路径为什么取不到图片？images文件夹和app文件夹是平级的，我可以用../../app/xxx.js取到app文件夹里面的js文件，那么为什么我不能用../../images/xxx.png??有没有人解答一下啊~

**Comment by balddonkey** [comment]
我使用 NowaGUI 创建的项目，根据readme要求放在images里面的。

**Comment by balddonkey** [comment]
@2999

**Comment by gbk** [comment]
可以取到的。确认一下你是怎么用的？
```
import imgData from '../../images/xxx.png';
...
<img src={imgData}/>
```
