### ISSUE TITLE
关于nowa server开启以后的问题

### ISSUE THREAD

**Issue by balddonkey** [saltjs/salt-ui#52]
开启以后，我在Dev网站配置了主页（例如：http://www.xxx.com?corpId=$CORPID$），我在刷新页面的时候由于Nowa server的缘故吧，开启服务访问链接地址以后会自动在地址后面追加一段随机字符串，致使我刷新的时候页面url改变了，然后拿改变以后的url去调用dd.ready的时候发生错误。这里唯一的区别是：第一次从企业界面进入微应用调用dd.ready的时候url没有后面的那一串随机字符串，刷新的时候后面有了这一串字符串，但是dd.config什么的都重新执行了，问题应该出在这串随机字符串上面，我有什么办法可以设置不生成这段随机字符串吗？？？

**Comment by balddonkey** [comment]
@2999

**Comment by gbk** [comment]
是 react-router 加的随机字符串
参考下面的代码修改：
```js
import { useRouterHistory } from 'react-router';
import createHashHistory from 'history/lib/createHashHistory';
customHistory = useRouterHistory(createHashHistory)({ queryKey: false });
...
<Router history={customHistory}>
```
