### ISSUE TITLE
slide 图片不显示

### ISSUE THREAD

**Issue by QinneChen** [saltjs/salt-ui#54]
控制台报错
salt-ui.min.js:7 Uncaught TypeError: Cannot read property 'classList' of undefined
at t.value (salt-ui.min.js:7)

**Comment by gbk** [comment]
是否能给出可还原问题的 demo？

**Comment by QinneChen** [comment]
我直接用的slide的demo,那个例子中的style={{backgroundImage:'1.png'}}不显示，
但是我用 let img1 = require('./../../images/1.png'); img src={img1}可以显示，说明图片是引用到了的

**Comment by QinneChen** [comment]
现象就是界面无报错，图片不显示，谷歌控制台报错Uncaught TypeError: Cannot read property 'classList' of undefined

**Comment by gbk** [comment]
https://salt-ui.github.io/components/tingle-slide
你参考的是哪个 demo 呢，以官方站点文档为准吧

**Comment by QinneChen** [comment]
感谢，我参考的是这个saltjs/salt-ui wki

**Comment by gbk** [comment]
好的，我把 wiki 更新了。
