### ISSUE TITLE
项目build后代码没有强压缩

### ISSUE THREAD

**Issue by semdy** [saltjs/salt-ui#57]
项目build后，代码只是格式形式的压缩，没有混淆强压缩，难道需要自己添加uglify插件吗？

**Comment by gbk** [comment]
为避免混淆带来的风险，默认不开启 mangle，如需开启请执行以下命令来构建：
```shell
nowa build --mangle
```
参考文档 https://nowa-webpack.github.io/docs/xiang_mu_gou_jian.html
