### ISSUE TITLE
tingle-scroll-list依赖包添加不了，这是什么情况

### ISSUE THREAD

**Issue by z810276431** [saltjs/salt-ui#60]
如题，nowaGUI添加该依赖时不成功

**Comment by gbk** [comment]
有没有截图？

cc @Jirapo

**Comment by z810276431** [comment]
@gbk 
![v qx17a5oboz5jf86ke mkc](https://user-images.githubusercontent.com/16434735/28298479-129776da-6ba6-11e7-8dac-bcde09ffdb72.png)
![ttq55 iyqau jz4u xw d](https://user-images.githubusercontent.com/16434735/28298507-3aeee096-6ba6-11e7-8e49-17182a6955b1.png)

**Comment by gbk** [comment]
@z810276431 你在安装一个不存在的模块。
SaltUI（原 tingle）的开源仍在进行中，[官网](https://salt-ui.github.io/)也在建设中，目前还不支持通过 npm 包的方式引用去使用组件，请参考官网的 demo，直接使用 cdn 上的 js 大包。

**Comment by z810276431** [comment]
@gbk 我看官网上就是直接instal的，而且demo好像没有关于scroll-list相关的demo，是直接用saltUi.js么，有没有相关的例子demo可以给我参考一下，谢谢了

**Comment by z810276431** [comment]
@gbk 
function getJsonp(page, size) {
  const now = (new Date()).getTime();
  const url = `http://dip.alibaba-inc.com/api/v2/services/schema/mock/36906.jsonp?callback=jsonpCallbak&currentPage=${page}&pageSize=${size}&rnd=${now}`;
  const script = document.createElement('script');
  script.src = url;
  document.head.appendChild(script);
}
请问这个种的url返回的数据格式是什么，我这边一直js报错

**Comment by gbk** [comment]
@2999 scroll-list 的文档要更新一下啦

@z810276431 请加钉钉群提问吧
![image](https://user-images.githubusercontent.com/865717/28345641-44f6d52c-6c5e-11e7-9227-59607c306477.png)
