### ISSUE TITLE
FAQ: salt-ui.min.js正确的引入方式

### ISSUE THREAD

**Issue by susliang** [saltjs/salt-ui#61]
![default](https://user-images.githubusercontent.com/6409597/29361869-021c909c-82bc-11e7-94f5-417ffc4a4975.png)
![1](https://user-images.githubusercontent.com/6409597/29361871-0489f66c-82bc-11e7-9ba2-1386d204ef03.png)
（1）在html通过<script>标签，会提示createClass is not a function
（2）在入口文件中，通过import方式引入，会提示reactDOM未定义
以我的理解是，在引入saltui.js之前要确保react以及react-dom先引入，所以请大神们指教，有没有什么更好的引入方式呢？

**Comment by 2999** [comment]
在引入salt-ui之前，先通过<script>方式引入react

**Comment by WangYang-Rex** [comment]
使用script标签引入react，react-dom等感觉有点挫，不能把所有代码打包到一起，目前可否有解决方案
