### ISSUE TITLE
没有开源吗？

### ISSUE THREAD

**Issue by fall-wind** [saltjs/salt-ui#63]
没有开源吗？

**Comment by WangYang-Rex** [comment]
同问，何时开源呢

**Comment by gbk** [comment]
https://github.com/saltjs/salt-ui/issues/43#issuecomment-327661731

**Comment by WangYang-Rex** [comment]
@gbk 现在9月份了，貌似还没开源，saltui真的很需要按需加载，不然性能上的问题会比较严重

**Comment by gbk** [comment]
@2999

**Comment by 2999** [comment]
@yt1520406335 @WangYang-Rex https://github.com/salt-ui/saltui
