### ISSUE TITLE
开发环境

### ISSUE THREAD

**Issue by huaxiaoxi** [saltjs/salt-ui#9]
开发环境的链接打不开？

**Comment by gbk** [comment]
具体是哪个链接？能不能贴出来？

**Comment by huaxiaoxi** [comment]
http://ux.alibaba.net/products/nowa.html

**Comment by gbk** [comment]
这个链接我们并没有公布出去，可以告诉我你在哪里找到的吗？
如果你是 saltui 的开发者，可以参考这个项目：https://github.com/saltjs/salt-ui/tree/master/demo

**Comment by huaxiaoxi** [comment]
http://gitlab.alibaba-inc.com/uxcore/uxcore-kuma/tree/master 这个链接也打不开，就是在demo的readme说明中的 环境准备和CSS约定 下的链接。

**Comment by gbk** [comment]
很抱歉，demo 的 README 已更新。
